version: '3.8'

services:
  # DB
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: ${POSTGRES_USER}          
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

      # mount SQL script to init folder
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - plant-net
    restart: always

  # Backend
  backend:
    build: ./PlantMonitoringAPI
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}"
    depends_on:
      - postgres
    networks:
      - plant-net
    restart: always

  # Frontend and proxy
  frontend:
    build: ./plantmonitoring_frontend
    ports:
      - "80:80"  # expose Port 80 of container to port 80 VM
    depends_on:
      - backend
    networks:
      - plant-net
    restart: always

networks:
  plant-net: